//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbWaterBillEntities : DbContext
    {
        public DbWaterBillEntities()
            : base("name=DbWaterBillEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Bill> Tb_Bill { get; set; }
        public virtual DbSet<Tb_Calculate> Tb_Calculate { get; set; }
        public virtual DbSet<Tb_Login> Tb_Login { get; set; }
        public virtual DbSet<NerkhMasraf> NerkhMasraf { get; set; }
        public virtual DbSet<Tb_Receipt> Tb_Receipt { get; set; }
        public virtual DbSet<Tb_Debt> Tb_Debt { get; set; }
        public virtual DbSet<Tb_CountBill> Tb_CountBill { get; set; }
        public virtual DbSet<Tb_Company> Tb_Company { get; set; }
        public virtual DbSet<Tb_FirstOptions> Tb_FirstOptions { get; set; }
        public virtual DbSet<Tb_Receipt_calc> Tb_Receipt_calc { get; set; }
        public virtual DbSet<Tb_PanelSms> Tb_PanelSms { get; set; }
        public virtual DbSet<Tb_OptionsSms> Tb_OptionsSms { get; set; }
    }
}
