//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NerkhMasraf
    {
        public string TypeName { get; set; }
        public double Curency { get; set; }
    }
}
