//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Bill()
        {
            this.Tb_Receipt = new HashSet<Tb_Receipt>();
        }
    
        public int BillId { get; set; }
        public System.DateTime SeenDate { get; set; }
        public string Describtion { get; set; }
        public int SubScribCode { get; set; }
        public double MeterNumberPast { get; set; }
        public double MeterNumberNow { get; set; }
        public string NameCompany { get; set; }
        public string SeenDateShamsi { get; set; }
        public int PelackNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Receipt> Tb_Receipt { get; set; }
        public virtual Tb_Company Tb_Company1 { get; set; }
    }
}
