//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Calculate
    {
        public int CalculateId { get; set; }
        public double Bedehi { get; set; }
        public double Bestankar { get; set; }
        public double UnitPay { get; set; }
        public double SumMaliat { get; set; }
        public double SumTotal { get; set; }
        public int SubscribCode { get; set; }
    
        public virtual Tb_Company Tb_Company1 { get; set; }
    }
}
