//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Company()
        {
            this.Tb_Bill = new HashSet<Tb_Bill>();
            this.Tb_Calculate = new HashSet<Tb_Calculate>();
        }
    
        public int SubscribId { get; set; }
        public string CompanyName { get; set; }
        public int PelakId { get; set; }
        public string PhoneNumber { get; set; }
        public string Addres { get; set; }
        public string TypePublicService { get; set; }
        public string FatherName { get; set; }
        public int Shenasname { get; set; }
        public string Codemeli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Bill> Tb_Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Calculate> Tb_Calculate { get; set; }
        public virtual Tb_Debt Tb_Debt { get; set; }
    }
}
