//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Debt
    {
        public int ID { get; set; }
        public Nullable<double> Debt { get; set; }
        public Nullable<double> Best { get; set; }
    
        public virtual Tb_Company Tb_Company1 { get; set; }
    }
}
