//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_FirstOptions
    {
        public byte Id { get; set; }
        public double Abunman { get; set; }
        public double Maliat { get; set; }
        public double PublicWork { get; set; }
        public double GhotreEnsheab { get; set; }
        public double CurencuOfUnit { get; set; }
        public double CurencuOfUnitToUp { get; set; }
        public string HesabPhone { get; set; }
    }
}
