//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PanelSms
    {
        public long Key { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public string NameCustomer { get; set; }
        public Nullable<System.DateTime> DateSms { get; set; }
    }
}
