//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Receipt_calc
    {
        public long Key { get; set; }
        public Nullable<int> Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> bedehi { get; set; }
        public Nullable<int> paradakhti { get; set; }
        public Nullable<System.DateTime> datesabt { get; set; }
        public string type { get; set; }
    }
}
