//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBill_DataLayer.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Receipt
    {
        public double Id { get; set; }
        public int SubaScribId { get; set; }
        public int PelakNumber { get; set; }
        public string SubName { get; set; }
        public System.DateTime DatePast { get; set; }
        public System.DateTime DateNow { get; set; }
        public double MeterPast { get; set; }
        public double MeterNow { get; set; }
        public int AmountLevel { get; set; }
        public string LeterCurency { get; set; }
        public double NumberCurency { get; set; }
        public Nullable<double> Abounman { get; set; }
        public string Penalty { get; set; }
        public Nullable<double> Maliat { get; set; }
        public double PublicWork { get; set; }
        public string CurencyPay { get; set; }
        public double Ghotre { get; set; }
        public string DeadlineCurency { get; set; }
        public string HesabNumber { get; set; }
        public Nullable<double> Debt { get; set; }
        public int Curency { get; set; }
        public string PhoneNumber { get; set; }
        public string DateShamsi { get; set; }
        public double Bestan { get; set; }
        public double CurencyinDore { get; set; }
        public string FatherName { get; set; }
        public int Shenasname { get; set; }
        public string Adress { get; set; }
        public string codemeli { get; set; }
        public string pay2 { get; set; }
        public string pay3 { get; set; }
    
        public virtual Tb_Bill Tb_Bill { get; set; }
    }
}
